shim-version: v0.3.18@sha256:7d9f98be78c91ede89f43c948a12d084fae34312effe9395ca7ed572991cb561
cvm-version: 0.6.7
cpus: 4
memory: 16384

containers:
  - name: "function"
    image: "ghcr.io/tinfoilsh/system-prompt-injector:0.0.14@sha256:3b096c221a51df6980b8a3b061a4fdefd5988b3135ebe096347464b1630dd32d"
    env:
      - TINFOIL_INFERENCE_URL: "https://inference.tinfoil.sh"
    secrets:
      - SYSTEM_PROMPT_TEMPLATE

shim:
  listen-port: 443
  upstream-port: 8080
  paths:
    - /healthz
    - /v1/chat/completions
